package com.medicore.repository;

import com.medicore.model.Bed;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

import java.util.List;
import java.util.Optional;

/**
 * ✅ BedRepository — Spring Data JPA
 *
 * All method bodies are auto-generated by Spring at runtime.
 * Maps to MySQL `beds` table via Hibernate.
 */
@Repository
public interface BedRepository extends JpaRepository<Bed, Long> {

    /**
     * SELECT * FROM beds WHERE status = ?
     * Example: findByStatus("AVAILABLE") → all free beds
     */
    List<Bed> findByStatus(String status);

    /**
     * SELECT * FROM beds WHERE bed_id = ?
     * Returns Optional — handles "bed not found" gracefully.
     */
    Optional<Bed> findByBedId(String bedId);

    /**
     * SELECT COUNT(*) FROM beds WHERE status = ?
     */
    long countByStatus(String status);

    /**
     * SELECT * FROM beds WHERE ward = ?
     * Used to group beds by ward in the Bed Map panel.
     */
    List<Bed> findByWard(String ward);

    /**
     * SELECT * FROM beds ORDER BY bed_id ASC
     * Used to display beds in sorted order on the dashboard.
     */
    List<Bed> findAllByOrderByBedIdAsc();

    /**
     * SELECT * FROM beds WHERE ward = ? ORDER BY bed_id ASC
     */
    List<Bed> findByWardOrderByBedIdAsc(String ward);
}
